### ISSUE TITLE
Add optional pkgdown deployment job

### ISSUE THREAD

**Issue by sebble** [jumpingrivers/inteRgrate#18]
Configure with e.g., `DEPLOY_PKGDOWN=true`
Run after tagging?

### Option 1:

Build pkgdown in CI task
Use Connect app API to create or identify existing app
Update Connect custom URL with API
Use Connect bundle deployment API to push new tar file (https://rstudio.github.io/connectapi/#deployment)

### Option 2:

Provide `Makefile` and `manifest.json` to be stored in e.g., `~/docs` directory of original source of package?
Use Connect app API to create or identify existing app
Update Connect custom URL with API
Trigger git deploy or rebuild on Connect using API

### Option 3:

Create/update a dedicated branch for pkdown documentation, like gh-pages
[optional] trigger initial Connect deployment or forced update

### Questions

- Is this suitable for inteRgrate or is it too specific to JR?
- Where to configure Connect API URL and API token?
- Does `https://github.com/ropenscilabs/tic.package` help? (uses dedicated branch)

**Comment by csgillespie** [comment]
Don't think this would be part of inteRgrate. 

Closing, out of scope
