### ISSUE TITLE
check_version checks against previous commit ot master, rather than checking against tag on repo. 

### ISSUE THREAD

**Issue by jracpatt** [jumpingrivers/inteRgrate#31]
If the definition of a 'version' is a tag on the repo, then the definition of whether a given commit is a different 'version' is whether the version number of that commit is different from the version number of the previous tag, if it exists. If no tags exist, then it should be judged that there is no previous version with which to compare the version and the check should accept the version number. 

https://github.com/jumpingrivers/inteRgrate/blob/master/R/check_version.R

**Comment by csgillespie** [comment]
We have two different ideas' of version:

- X.Y.Z - a release version. This should always be tagged
- X.Y.Z.900W - a dev version. This should never be tagged

Following that, how does your question change (and should the docs change)
