### ISSUE TITLE
check_lintr() pulls up R/sysdata.rda for no newline

### ISSUE THREAD

**Issue by aj-sykes92** [jumpingrivers/inteRgrate#33]
Adding internal package data with `usethis::use_data(..., internal = TRUE)` creates **R/sysdata.rda**.

`inteRgrate::check_lintr()` runs `inteRgrate:::readLines()` on all files in **R/** (check_lintr.R lines 57--58)  and throws a warning for no newline at end of file for **sysdata.rda** file. I could be wrong but I don't think this can/should be fixed directly.

Adding to .lintr exclusions doesn't work in this instance since the code is applied to all files in the R directory regardless.

Suggest perhaps modify line 57 to include .lintr exclusions/include only *.R files?

**Comment by csgillespie** [comment]
Thanks. Should be fixed in the dev branch.
